### ISSUE TITLE
[Bug] In groups, Italian language is forced

### ISSUE THREAD

**Issue by rafitamolin** [MatteoSid/calliope#4]
No matter what language you speak, it's being translated into Italian and there is no way to change the language or make the bot auto detect it.

**Comment by MatteoSid** [comment]
> No matter what language you speak, it's being translated into Italian and there is no way to change the language or make the bot auto detect it.

Are you using my Calliope bot or are you try it in you're local machine?

**Comment by rafitamolin** [comment]
> Are you using my Calliope bot or are you try it in you're local machine?

I'm using your Calliope bot. In private messaging it's fine as it autodetects the audio language, but in groups it's forced to Italian no matter what language is being spoken.

**Comment by MatteoSid** [comment]
> > Are you using my Calliope bot or are you try it in you're local machine?
> 
> 
> 
> I'm using your Calliope bot. In private messaging it's fine as it autodetects the audio language, but in groups it's forced to Italian no matter what language is being spoken.

Use the command _/language en_ to force the language in the groups. You can sobstitute "en" with the language that you prefer.

**Comment by rafitamolin** [comment]
> Use the command _/language en_ to force the language in the groups. You can sobstitute "en" with the language that you prefer.

Perfect, thank you very much! Didn't know that command was available. Thanks for the great bot.

**Comment by MatteoSid** [comment]
> > Use the command _/language en_ to force the language in the groups. You can sobstitute "en" with the language that you prefer.
> 
> 
> 
> Perfect, thank you very much! Didn't know that command was available. Thanks for the great bot.

You're welcome. It's a preview feature so nobody knows that there is this command
